'use client';

import { useState, useEffect, useCallback } from 'react';
import {
  getSearchInfo, testAtlasIndex, testVectorIndex,
  getScanRules, updateScanRules, resetScanRules,
} from '../../lib/api';

/* ── Friendly labels for keys ─────────────────────────────────────── */
const MODULE_LABELS = {
  dgaDetection: 'DGA Detection',
  homoglyphDetection: 'Homoglyph Detection',
  brandImpersonation: 'Brand Impersonation',
  phishingKeywords: 'Phishing Keywords',
  structuralBypass: 'Structural Bypass',
  vectorSearch: 'Vector Search',
  threatIntel: 'Threat Intel Lookup',
};

const WEIGHT_LABELS = {
  domainAge: 'Domain Age',
  ssl: 'SSL Certificate',
  entropy: 'URL Entropy',
  dns: 'DNS Indicators',
  hosting: 'Hosting Reputation',
  vectorSimilarity: 'Vector Similarity',
  dgaScore: 'DGA Score',
  structuralScore: 'Structural Score',
  homoglyphScore: 'Homoglyph Score',
  brandImpersonation: 'Brand Impersonation',
};

const THRESHOLD_LABELS = {
  blockScore: 'Block Score',
  reviewScore: 'Review Score',
  classifyPhishing: 'Classify → Phishing',
  classifyMalware: 'Classify → Malware',
  classifySuspicious: 'Classify → Suspicious',
  threatIntelMinScore: 'Threat Intel Min Score',
  vectorSearchLimit: 'Vector Search Limit',
};

const HARD_FLOOR_LABELS = {
  homoglyphVisualSimilarity: 'Homoglyph Visual Similarity',
  brandDist1: 'Brand Distance 1',
  brandDist1WithKeywords: 'Brand Dist 1 + Keywords',
  brandDist2: 'Brand Distance 2',
  brandDist2WithKeywords: 'Brand Dist 2 + Keywords',
  brandDist3WithKeywords: 'Brand Dist 3 + Keywords',
};

/* ── Info descriptions + examples for every rule ──────────────────── */
const RULE_INFO = {
  // Detection Modules
  dgaDetection: {
    desc: 'Detects domains generated by algorithms (DGA) used by malware to create random-looking command-and-control domains.',
    example: 'xk7q2m9z4p.tk — random consonant clusters and low English bigram frequency indicate machine generation.',
  },
  homoglyphDetection: {
    desc: 'Detects visually deceptive characters that mimic legitimate domains. Attackers substitute look-alike Unicode or similar characters.',
    example: 'gооgle.com (Cyrillic "о") looks identical to google.com but is a completely different domain.',
  },
  brandImpersonation: {
    desc: 'Measures Levenshtein edit distance between the scanned domain and known brand/government domains to detect typosquatting.',
    example: 'rbl.org.in is 1 character away from rbi.org.in (Reserve Bank of India) — likely a typosquat.',
  },
  phishingKeywords: {
    desc: 'Checks if the URL path or domain contains keywords commonly associated with credential-harvesting phishing pages.',
    example: 'rbi-secure-login-verify.xyz — contains "secure", "login", and "verify", all common phishing lures.',
  },
  structuralBypass: {
    desc: 'Detects URL manipulation techniques used to bypass security filters — excessive subdomains, encoded characters, embedded credentials.',
    example: 'http://admin%40gov.in@evil.com/update — uses @ to trick users into thinking the domain is gov.in.',
  },
  vectorSearch: {
    desc: 'Uses AI embeddings to find previously scanned URLs that are semantically similar to the current URL, even if they look different textually.',
    example: 'Scanning nic-gov-portal.tk finds 94% similarity to previously blocked nic-login-portal.ml.',
  },
  threatIntel: {
    desc: 'Cross-references the URL against external threat intelligence feeds (known phishing campaigns, malware C2, blocklists).',
    example: 'URL matches a known Lazarus Group C2 domain pattern from CERT-IN feed with 0.92 confidence.',
  },
  // Risk Weights
  domainAge: {
    desc: 'How much the domain\'s registration age affects the risk score. Newly registered domains are riskier.',
    example: 'A domain registered 3 days ago scores 1.0 (max risk). A 5-year-old domain scores 0.1.',
  },
  ssl: {
    desc: 'How much SSL certificate validity affects risk. Missing or invalid SSL is a red flag.',
    example: 'A phishing site at http://rbi-login.xyz with no SSL gets ssl_score = 1.0.',
  },
  entropy: {
    desc: 'How much URL randomness (Shannon entropy) affects risk. High entropy suggests algorithmically generated URLs.',
    example: 'xk7q2m9z4p5w.tk has entropy 4.8 (high risk) vs. google.com at 2.5 (normal).',
  },
  dns: {
    desc: 'How much the DNS status contributes to risk. Suspended or parked domains are riskier than active ones.',
    example: 'A domain with DNS status "suspended" gets dns_score = 0.9. An "active" domain gets 0.2.',
  },
  hosting: {
    desc: 'How much hosting infrastructure signals contribute. Shared hosting, suspicious TLDs, and IP-based domains increase risk.',
    example: 'Shared hosting + suspicious .tk TLD + IP address in domain → hosting_score = 1.0.',
  },
  vectorSimilarity: {
    desc: 'How much embedding similarity to known threats affects the score. Higher weight makes the system trust vector evidence more.',
    example: 'If a URL is 92% similar to a known phishing URL, this weight determines how much that 0.92 score contributes.',
  },
  dgaScore: {
    desc: 'How much the DGA detection confidence contributes to overall risk.',
    example: 'DGA detector returns 0.85 confidence → this weight controls how much that 0.85 affects the final score.',
  },
  structuralScore: {
    desc: 'How much structural bypass techniques contribute to overall risk.',
    example: 'URL uses @ trick + hex encoding + 5 subdomains → structural score 0.9, multiplied by this weight.',
  },
  homoglyphScore: {
    desc: 'How much visual impersonation via homoglyph characters contributes to risk.',
    example: 'Domain uses Cyrillic "а" instead of Latin "a" with 0.95 visual similarity → multiplied by this weight.',
  },
  // Thresholds
  blockScore: {
    desc: 'Risk score at or above which the system recommends blocking the URL immediately.',
    example: 'With blockScore = 75: a URL scoring 78 gets "block" action. At 74 it gets "review" instead.',
  },
  reviewScore: {
    desc: 'Risk score at or above which the system flags the URL for manual analyst review.',
    example: 'With reviewScore = 50: a URL scoring 55 gets "review". Below 50 gets "allow".',
  },
  classifyPhishing: {
    desc: 'Score threshold to classify a URL as phishing (highest severity).',
    example: 'With threshold = 80: a URL scoring 82 is classified as "phishing". At 79 it becomes "malware".',
  },
  classifyMalware: {
    desc: 'Score threshold to classify a URL as malware distribution.',
    example: 'With threshold = 60: a URL scoring 65 is classified as "malware". At 59 it becomes "suspicious".',
  },
  classifySuspicious: {
    desc: 'Score threshold to classify a URL as suspicious (warrants investigation).',
    example: 'With threshold = 40: a URL scoring 45 is "suspicious". Below 40 is classified as "benign".',
  },
  threatIntelMinScore: {
    desc: 'Minimum confidence score for a threat intel feed match to be included in results. Lower = more matches but more noise.',
    example: 'At 0.85: only high-confidence intel matches are shown. At 0.5: weaker matches also appear.',
  },
  vectorSearchLimit: {
    desc: 'Maximum number of similar URLs to retrieve from vector search per scan.',
    example: 'At 5: the scanner returns up to 5 most similar known threats. At 10: more context but slower.',
  },
  // Hard Floors
  homoglyphVisualSimilarity: {
    desc: 'Minimum risk score when a confirmed homoglyph impersonation is detected with high visual similarity (≥ 60%).',
    example: 'gооgle.com (Cyrillic) has 95% visual similarity → risk cannot drop below 75, even if all other signals are benign.',
  },
  brandDist1: {
    desc: 'Minimum risk score when a domain is exactly 1 edit distance from a known brand (strongest typosquat signal).',
    example: 'rbl.org.in is 1 char from rbi.org.in → floor of 78 ensures it\'s always flagged for review.',
  },
  brandDist1WithKeywords: {
    desc: 'Minimum risk score when 1-edit-distance typosquat also contains phishing keywords. Near-certain phishing.',
    example: 'rbl-login.org.in — 1 char from rbi.org.in AND contains "login" → floor 85, auto-blocked.',
  },
  brandDist2: {
    desc: 'Minimum risk score when a domain is 2 edits from a known brand.',
    example: 'rbb.org.in is 2 chars from rbi.org.in → floor of 60 ensures it gets at least "review".',
  },
  brandDist2WithKeywords: {
    desc: 'Minimum risk score when 2-edit-distance typosquat also contains phishing keywords.',
    example: 'rbb-verify.org.in — 2 edits from rbi.org.in + "verify" → floor 72.',
  },
  brandDist3WithKeywords: {
    desc: 'Minimum risk score when 3-edit-distance match contains phishing keywords. Weaker signal but keywords confirm intent.',
    example: 'rbx-login-update.tk — 3 edits from rbi.org.in but has "login" + "update" → floor 55.',
  },
};

/* ── Shared styles ────────────────────────────────────────────────── */
const cardStyle = {
  background: '#fff', borderRadius: 12, padding: 24,
  boxShadow: '0 1px 3px rgba(0,0,0,0.08)',
};
const btnPrimary = {
  padding: '8px 20px', borderRadius: 6,
  border: '1px solid #E8EDEB', background: '#016BF8',
  color: '#fff', fontSize: 13, fontWeight: 600, cursor: 'pointer',
};
const btnDanger = {
  ...btnPrimary, background: '#CF4A22', border: '1px solid #CF4A22',
};
const btnSecondary = {
  ...btnPrimary, background: '#fff', color: '#1a1c1e', border: '1px solid #E8EDEB',
};
const sectionTitle = {
  fontSize: 14, fontWeight: 600, marginBottom: 12, color: '#1a1c1e',
};
const labelRow = {
  display: 'flex', alignItems: 'center', justifyContent: 'space-between',
  padding: '6px 0', borderBottom: '1px solid #F5F6F7', fontSize: 13,
};
const numInput = {
  width: 72, padding: '4px 8px', borderRadius: 6,
  border: '1px solid #E8EDEB', fontSize: 13, textAlign: 'right',
};
const tagStyle = {
  display: 'inline-flex', alignItems: 'center', gap: 6,
  padding: '4px 10px', borderRadius: 20, fontSize: 12,
  background: '#F5F6F7', color: '#1a1c1e',
};

/* ── Toggle switch ────────────────────────────────────────────────── */
function Toggle({ checked, onChange }) {
  return (
    <button
      type="button"
      onClick={() => onChange(!checked)}
      style={{
        width: 40, height: 22, borderRadius: 11, padding: 2,
        background: checked ? '#00684A' : '#ccc', border: 'none',
        cursor: 'pointer', transition: 'background .2s',
        display: 'flex', alignItems: 'center',
        justifyContent: checked ? 'flex-end' : 'flex-start',
      }}
    >
      <span style={{
        width: 18, height: 18, borderRadius: '50%', background: '#fff',
        boxShadow: '0 1px 3px rgba(0,0,0,.2)', transition: 'all .2s',
      }} />
    </button>
  );
}

/* ── Toast banner ─────────────────────────────────────────────────── */
function Toast({ message, type }) {
  if (!message) return null;
  const bg = type === 'error' ? '#FFEAE5' : '#E3FCF7';
  const fg = type === 'error' ? '#CF4A22' : '#00684A';
  return (
    <div style={{
      padding: '10px 16px', borderRadius: 8, background: bg,
      color: fg, fontSize: 13, fontWeight: 500, marginBottom: 16,
    }}>
      {message}
    </div>
  );
}

/* ── Info tooltip (ℹ button with popover) ─────────────────────────── */
function InfoTip({ ruleKey }) {
  const [open, setOpen] = useState(false);
  const info = RULE_INFO[ruleKey];
  if (!info) return null;

  return (
    <span style={{ position: 'relative', display: 'inline-flex', alignItems: 'center', marginLeft: 6 }}>
      <button
        type="button"
        onClick={e => { e.stopPropagation(); setOpen(o => !o); }}
        onBlur={() => setTimeout(() => setOpen(false), 200)}
        aria-label={`Info about ${ruleKey}`}
        style={{
          width: 18, height: 18, borderRadius: '50%', border: '1.5px solid #016BF8',
          background: open ? '#016BF8' : '#fff', color: open ? '#fff' : '#016BF8',
          fontSize: 11, fontWeight: 700, lineHeight: '16px', textAlign: 'center',
          cursor: 'pointer', padding: 0, fontFamily: 'Georgia, serif',
          transition: 'all .15s',
        }}
      >
        i
      </button>
      {open && (
        <div style={{
          position: 'absolute', left: 24, top: -8, zIndex: 50,
          width: 340, padding: 14, borderRadius: 10,
          background: '#1a1c1e', color: '#E8EDEB',
          boxShadow: '0 8px 24px rgba(0,0,0,.25)',
          fontSize: 12, lineHeight: 1.6,
        }}>
          <div style={{ marginBottom: 8 }}>{info.desc}</div>
          <div style={{
            padding: '8px 10px', borderRadius: 6, background: 'rgba(255,255,255,.08)',
            fontFamily: 'monospace', fontSize: 11, color: '#00ED64', wordBreak: 'break-word',
          }}>
            <span style={{ color: '#5C6C75', fontFamily: 'inherit' }}>Example: </span>
            {info.example}
          </div>
          <div style={{
            position: 'absolute', left: -5, top: 14,
            width: 10, height: 10, background: '#1a1c1e',
            transform: 'rotate(45deg)',
          }} />
        </div>
      )}
    </span>
  );
}

/* ================================================================== */
export default function SettingsPage() {
  /* system status */
  const [info, setInfo] = useState(null);
  const [atlasTest, setAtlasTest] = useState(null);
  const [vectorTest, setVectorTest] = useState(null);
  const [sysLoading, setSysLoading] = useState(true);

  /* scan rules */
  const [rules, setRules] = useState(null);
  const [dirty, setDirty] = useState(false);
  const [saving, setSaving] = useState(false);
  const [toast, setToast] = useState({ message: '', type: '' });
  const [newKeyword, setNewKeyword] = useState('');
  const [newTld, setNewTld] = useState('');
  const [tab, setTab] = useState('system'); // system | rules

  /* ── load data ─────────────────────────────────────────────────── */
  useEffect(() => {
    getSearchInfo()
      .then(res => setInfo(res.data))
      .catch(() => setInfo({ error: 'Failed to load' }))
      .finally(() => setSysLoading(false));

    getScanRules()
      .then(res => setRules(res.data))
      .catch(() => setToast({ message: 'Failed to load scan rules', type: 'error' }));
  }, []);

  /* ── helpers ────────────────────────────────────────────────────── */
  const flash = useCallback((msg, type = 'success') => {
    setToast({ message: msg, type });
    setTimeout(() => setToast({ message: '', type: '' }), 3000);
  }, []);

  const patch = useCallback((section, key, value) => {
    setRules(prev => ({
      ...prev,
      [section]: { ...prev[section], [key]: value },
    }));
    setDirty(true);
  }, []);

  const patchList = useCallback((section, list) => {
    setRules(prev => ({ ...prev, [section]: list }));
    setDirty(true);
  }, []);

  /* ── save / reset ──────────────────────────────────────────────── */
  const handleSave = async () => {
    setSaving(true);
    try {
      const { _id, ...body } = rules;
      const res = await updateScanRules(body);
      setRules(res.data);
      setDirty(false);
      flash('Rules saved successfully');
    } catch {
      flash('Failed to save rules', 'error');
    } finally {
      setSaving(false);
    }
  };

  const handleReset = async () => {
    if (!confirm('Reset all scan rules to factory defaults?')) return;
    setSaving(true);
    try {
      const res = await resetScanRules();
      setRules(res.data);
      setDirty(false);
      flash('Rules reset to defaults');
    } catch {
      flash('Failed to reset rules', 'error');
    } finally {
      setSaving(false);
    }
  };

  /* ── index tests ───────────────────────────────────────────────── */
  const handleTestAtlas = async () => {
    setAtlasTest(null);
    try { setAtlasTest((await testAtlasIndex()).data); }
    catch (err) { setAtlasTest({ status: 'error', error: err.message }); }
  };
  const handleTestVector = async () => {
    setVectorTest(null);
    try { setVectorTest((await testVectorIndex()).data); }
    catch (err) { setVectorTest({ status: 'error', error: err.message }); }
  };

  /* ── weight helpers ────────────────────────────────────────────── */
  const weightSum = rules?.riskWeights
    ? Object.values(rules.riskWeights).reduce((s, v) => s + v, 0)
    : 0;

  /* ================================================================ */
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 24, maxWidth: 900 }}>

      {/* Tab bar */}
      <div style={{ display: 'flex', gap: 4, borderBottom: '2px solid #E8EDEB', paddingBottom: 0 }}>
        {[['system', 'System'], ['rules', 'Scan Rules']].map(([key, label]) => (
          <button
            key={key}
            onClick={() => setTab(key)}
            style={{
              padding: '10px 20px', fontSize: 14, fontWeight: 600, cursor: 'pointer',
              border: 'none', background: 'none',
              borderBottom: tab === key ? '2px solid #016BF8' : '2px solid transparent',
              color: tab === key ? '#016BF8' : '#5C6C75',
              marginBottom: -2,
            }}
          >
            {label}
          </button>
        ))}
      </div>

      {/* ─── SYSTEM TAB ──────────────────────────────────────────── */}
      {tab === 'system' && (
        <>
          {/* System Status */}
          <div style={cardStyle}>
            <h3 style={{ fontSize: 16, fontWeight: 600, marginBottom: 16 }}>System Status</h3>
            {sysLoading ? (
              <div style={{ color: '#5C6C75' }}>Loading...</div>
            ) : info?.error ? (
              <div style={{ color: '#CF4A22' }}>Backend not reachable. Ensure it is running on port 8000.</div>
            ) : (
              <div style={{ display: 'flex', flexDirection: 'column', gap: 12, fontSize: 13 }}>
                {[
                  ['Database', info?.database],
                  ['Total Documents', info?.urlsCollection?.totalDocuments?.toLocaleString()],
                  ['With Embeddings', info?.urlsCollection?.documentsWithEmbedding?.toLocaleString()],
                ].map(([l, v]) => (
                  <div key={l} style={labelRow}>
                    <span style={{ color: '#5C6C75' }}>{l}</span>
                    <span style={{ fontWeight: 600 }}>{v || '—'}</span>
                  </div>
                ))}
                {info?.services && Object.entries(info.services).map(([k, v]) => (
                  <div key={k} style={labelRow}>
                    <span style={{ color: '#5C6C75' }}>{k}</span>
                    <span style={{ fontWeight: 600, color: v === 'initialized' ? '#00684A' : '#CF4A22' }}>{v}</span>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Index Tests */}
          <div style={cardStyle}>
            <h3 style={{ fontSize: 16, fontWeight: 600, marginBottom: 16 }}>Search Index Tests</h3>
            <div style={{ display: 'flex', gap: 16 }}>
              {[
                { label: 'Test Atlas Search Index', handler: handleTestAtlas, result: atlasTest },
                { label: 'Test Vector Search Index', handler: handleTestVector, result: vectorTest },
              ].map(({ label, handler, result }) => (
                <div key={label} style={{ flex: 1 }}>
                  <button onClick={handler} style={btnPrimary}>{label}</button>
                  {result && (
                    <div style={{
                      marginTop: 12, padding: 12, borderRadius: 8,
                      background: result.reachable ? '#E3FCF7' : '#FFEAE5',
                      color: result.reachable ? '#00684A' : '#CF4A22', fontSize: 12,
                    }}>
                      {result.reachable
                        ? `✓ Index "${result.indexName}" is reachable`
                        : `✗ Index unreachable: ${result.error || 'unknown'}`}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>

          {/* Environment Info */}
          <div style={cardStyle}>
            <h3 style={{ fontSize: 16, fontWeight: 600, marginBottom: 16 }}>Configuration</h3>
            <div style={{
              padding: 16, borderRadius: 8, background: '#1a1c1e',
              color: '#00ED64', fontFamily: 'monospace', fontSize: 12,
              lineHeight: 1.8, overflowX: 'auto',
            }}>
              <div>MONGODB_URI=mongodb+srv://***@cluster.mongodb.net/</div>
              <div>DB_NAME=shieldnet-ai</div>
              <div>VOYAGE_AI_API_KEY=***</div>
              <div>ATLAS_SEARCH_INDEX=url_search_index</div>
              <div>VECTOR_SEARCH_INDEX=url_vector_index</div>
              <div>FRONTEND_URL=http://localhost:3000</div>
            </div>
            <p style={{ fontSize: 12, color: '#5C6C75', marginTop: 12 }}>
              Configure these variables in your <code>.env</code> file in the project root.
            </p>
          </div>
        </>
      )}

      {/* ─── SCAN RULES TAB ──────────────────────────────────────── */}
      {tab === 'rules' && (
        <>
          <Toast message={toast.message} type={toast.type} />

          {!rules ? (
            <div style={cardStyle}><span style={{ color: '#5C6C75' }}>Loading rules...</span></div>
          ) : (
            <>
              {/* Action bar */}
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <div style={{ fontSize: 13, color: '#5C6C75' }}>
                  {dirty && <span style={{ color: '#CF4A22', fontWeight: 600 }}>● Unsaved changes</span>}
                </div>
                <div style={{ display: 'flex', gap: 8 }}>
                  <button onClick={handleReset} style={btnDanger} disabled={saving}>Reset to Defaults</button>
                  <button onClick={handleSave} style={btnPrimary} disabled={saving || !dirty}>
                    {saving ? 'Saving...' : 'Save Rules'}
                  </button>
                </div>
              </div>

              {/* ── Detection Modules ──────────────────────────── */}
              <div style={cardStyle}>
                <h4 style={sectionTitle}>Detection Modules</h4>
                <p style={{ fontSize: 12, color: '#5C6C75', marginBottom: 12 }}>
                  Enable or disable individual detection modules in the scan pipeline.
                </p>
                {rules.detectionModules && Object.keys(MODULE_LABELS).map(key => (
                  <div key={key} style={labelRow}>
                    <span style={{ display: 'flex', alignItems: 'center' }}>{MODULE_LABELS[key]}<InfoTip ruleKey={key} /></span>
                    <Toggle
                      checked={rules.detectionModules[key]}
                      onChange={v => patch('detectionModules', key, v)}
                    />
                  </div>
                ))}
              </div>

              {/* ── Risk Weights ───────────────────────────────── */}
              <div style={cardStyle}>
                <h4 style={sectionTitle}>Risk Weights</h4>
                <p style={{ fontSize: 12, color: '#5C6C75', marginBottom: 12 }}>
                  Weights for each risk factor. Should sum to ~1.0.
                  Current sum: <strong style={{ color: Math.abs(weightSum - 1) < 0.05 ? '#00684A' : '#CF4A22' }}>
                    {weightSum.toFixed(2)}
                  </strong>
                </p>
                {rules.riskWeights && Object.keys(WEIGHT_LABELS).map(key => (
                  <div key={key} style={labelRow}>
                    <span style={{ display: 'flex', alignItems: 'center' }}>{WEIGHT_LABELS[key]}<InfoTip ruleKey={key} /></span>
                    <input
                      type="number"
                      step="0.01"
                      min="0"
                      max="1"
                      value={rules.riskWeights[key] ?? 0}
                      onChange={e => patch('riskWeights', key, parseFloat(e.target.value) || 0)}
                      style={numInput}
                    />
                  </div>
                ))}
              </div>

              {/* ── Thresholds ─────────────────────────────────── */}
              <div style={cardStyle}>
                <h4 style={sectionTitle}>Thresholds</h4>
                <p style={{ fontSize: 12, color: '#5C6C75', marginBottom: 12 }}>
                  Score boundaries for classification, blocking, and review decisions.
                </p>
                {rules.thresholds && Object.keys(THRESHOLD_LABELS).map(key => {
                  const isFloat = key === 'threatIntelMinScore';
                  return (
                    <div key={key} style={labelRow}>
                      <span style={{ display: 'flex', alignItems: 'center' }}>{THRESHOLD_LABELS[key]}<InfoTip ruleKey={key} /></span>
                      <input
                        type="number"
                        step={isFloat ? '0.01' : '1'}
                        min="0"
                        max={isFloat ? '1' : '100'}
                        value={rules.thresholds[key] ?? 0}
                        onChange={e => {
                          const v = isFloat ? parseFloat(e.target.value) : parseInt(e.target.value, 10);
                          patch('thresholds', key, v || 0);
                        }}
                        style={numInput}
                      />
                    </div>
                  );
                })}
              </div>

              {/* ── Hard Floors ────────────────────────────────── */}
              <div style={cardStyle}>
                <h4 style={sectionTitle}>Hard Floors</h4>
                <p style={{ fontSize: 12, color: '#5C6C75', marginBottom: 12 }}>
                  Minimum risk score overrides. When a condition matches, the score will never drop below this value.
                </p>
                {rules.hardFloors && Object.keys(HARD_FLOOR_LABELS).map(key => (
                  <div key={key} style={labelRow}>
                    <span style={{ display: 'flex', alignItems: 'center' }}>{HARD_FLOOR_LABELS[key]}<InfoTip ruleKey={key} /></span>
                    <input
                      type="number"
                      step="1"
                      min="0"
                      max="100"
                      value={rules.hardFloors[key] ?? 0}
                      onChange={e => patch('hardFloors', key, parseInt(e.target.value, 10) || 0)}
                      style={numInput}
                    />
                  </div>
                ))}
              </div>

              {/* ── Phishing Keywords ──────────────────────────── */}
              <div style={cardStyle}>
                <h4 style={sectionTitle}>Phishing Keywords</h4>
                <p style={{ fontSize: 12, color: '#5C6C75', marginBottom: 12 }}>
                  Keywords that boost risk score when found in URL domain or path.
                </p>
                <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8, marginBottom: 12 }}>
                  {(rules.phishingKeywords || []).map((kw, i) => (
                    <span key={kw} style={tagStyle}>
                      {kw}
                      <button
                        onClick={() => patchList('phishingKeywords', rules.phishingKeywords.filter((_, j) => j !== i))}
                        style={{
                          border: 'none', background: 'none', cursor: 'pointer',
                          color: '#CF4A22', fontWeight: 700, fontSize: 14, lineHeight: 1, padding: 0,
                        }}
                      >
                        ×
                      </button>
                    </span>
                  ))}
                </div>
                <div style={{ display: 'flex', gap: 8 }}>
                  <input
                    type="text"
                    placeholder="Add keyword..."
                    value={newKeyword}
                    onChange={e => setNewKeyword(e.target.value.toLowerCase())}
                    onKeyDown={e => {
                      if (e.key === 'Enter' && newKeyword.trim()) {
                        if (!rules.phishingKeywords.includes(newKeyword.trim())) {
                          patchList('phishingKeywords', [...rules.phishingKeywords, newKeyword.trim()]);
                        }
                        setNewKeyword('');
                      }
                    }}
                    style={{ ...numInput, width: 180, textAlign: 'left' }}
                  />
                  <button
                    onClick={() => {
                      if (newKeyword.trim() && !rules.phishingKeywords.includes(newKeyword.trim())) {
                        patchList('phishingKeywords', [...rules.phishingKeywords, newKeyword.trim()]);
                      }
                      setNewKeyword('');
                    }}
                    style={btnSecondary}
                  >
                    Add
                  </button>
                </div>
              </div>

              {/* ── Suspicious TLDs ───────────────────────────── */}
              <div style={cardStyle}>
                <h4 style={sectionTitle}>Suspicious TLDs</h4>
                <p style={{ fontSize: 12, color: '#5C6C75', marginBottom: 12 }}>
                  Top-level domains considered suspicious during scanning.
                </p>
                <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8, marginBottom: 12 }}>
                  {(rules.suspiciousTlds || []).map((tld, i) => (
                    <span key={tld} style={tagStyle}>
                      {tld}
                      <button
                        onClick={() => patchList('suspiciousTlds', rules.suspiciousTlds.filter((_, j) => j !== i))}
                        style={{
                          border: 'none', background: 'none', cursor: 'pointer',
                          color: '#CF4A22', fontWeight: 700, fontSize: 14, lineHeight: 1, padding: 0,
                        }}
                      >
                        ×
                      </button>
                    </span>
                  ))}
                </div>
                <div style={{ display: 'flex', gap: 8 }}>
                  <input
                    type="text"
                    placeholder=".example"
                    value={newTld}
                    onChange={e => setNewTld(e.target.value.toLowerCase())}
                    onKeyDown={e => {
                      if (e.key === 'Enter' && newTld.trim()) {
                        const val = newTld.trim().startsWith('.') ? newTld.trim() : '.' + newTld.trim();
                        if (!rules.suspiciousTlds.includes(val)) {
                          patchList('suspiciousTlds', [...rules.suspiciousTlds, val]);
                        }
                        setNewTld('');
                      }
                    }}
                    style={{ ...numInput, width: 180, textAlign: 'left' }}
                  />
                  <button
                    onClick={() => {
                      if (newTld.trim()) {
                        const val = newTld.trim().startsWith('.') ? newTld.trim() : '.' + newTld.trim();
                        if (!rules.suspiciousTlds.includes(val)) {
                          patchList('suspiciousTlds', [...rules.suspiciousTlds, val]);
                        }
                      }
                      setNewTld('');
                    }}
                    style={btnSecondary}
                  >
                    Add
                  </button>
                </div>
              </div>

              {/* Bottom save bar */}
              {dirty && (
                <div style={{
                  position: 'sticky', bottom: 0, background: '#fff',
                  padding: '12px 24px', borderRadius: 12,
                  boxShadow: '0 -2px 8px rgba(0,0,0,0.08)',
                  display: 'flex', justifyContent: 'flex-end', gap: 8,
                }}>
                  <button onClick={() => {
                    getScanRules().then(res => { setRules(res.data); setDirty(false); });
                  }} style={btnSecondary}>
                    Discard
                  </button>
                  <button onClick={handleSave} style={btnPrimary} disabled={saving}>
                    {saving ? 'Saving...' : 'Save Rules'}
                  </button>
                </div>
              )}
            </>
          )}
        </>
      )}
    </div>
  );
}
